[project]
name = "llmeval"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "jupyter>=1.1.1",
    "slurmpilot==0.1.5.dev0",
]
